driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/sanhak?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&connectTimeout=5000&socketTimeout=30000
user=root
password=btsjin7@34
